version: '3.8'

services:
  semantic-search:
    # Tells Docker to build the image from the Dockerfile in this directory
    build: .
    
    # Sets a name for the container
    container_name: semantic-search

    # Increase shutdown timeout
    stop_grace_period: 60s
    
    # Maps the host machine's port 5001 to the container's port 5001
    ports:
      - "5001:5001"
      
    # Data Persistence
    volumes:
      # Mounts local './data' folder into the container's '/app/data' folder.
      - ./data:/app/data
      
    # Restarts the container automatically if it crashes
    restart: unless-stopped