apiVersion: v1
data:
  PRETRAINED_SEARCH_MODEL: paraphrase-multilingual-mpnet-base-v2
  BATCH_PROCESS_INTERVAL: "600"
  CSV_FILE: synthetic-it-call-center-tickets.csv
  DEFAULT_BATCH_SIZE: "10000"
kind: ConfigMap
metadata:
  name: init-env-cm
