{{ range $key, $value := .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" $ }}-{{ $key }}-cm
  labels:
    {{- include "app.labels" $ | nindent 4 }}
data:
  {{- range $configKey, $configValue := $value }}
  {{ $configKey }}: "{{ $configValue }}"
  {{- end }}
---
{{ end }}