{{ range $key, $value := .Values.autoscaling }}
{{- if and $value.enabled (or $value.targetCPUUtilizationPercentage $value.targetMemoryUtilizationPercentage) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "app.fullname" $ }}-{{ $key }}-hpa
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "app.fullname" $ }}-{{ $key }}-deploy
  minReplicas: {{ $value.minReplicas }}
  maxReplicas: {{ $value.maxReplicas }}
  metrics:
    {{- if $value.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $value.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $value.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $value.targetMemoryUtilizationPercentage }}
    {{- end }}
---
{{- end }}
{{ end }}