{{ range $key, $value := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" $ }}-{{ $key }}-svc
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  type: {{ $value.type | default "ClusterIP" }}
  ports:
    - name: {{ $key }}-port-ext
      port: {{ $value.port }}
      targetPort: {{ default (printf "%s-port-int" $key) $value.targetPort }}
      protocol: TCP
  selector:
    {{- include "app.selectorLabels" $ | nindent 4 }}
---
{{ end }}
